package com.sbom;

import com.sbom.model.QueryResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Runs against real SBOMs generated by the CycloneDX Maven plugin:
 * sbom-cli itself (Spring Boot 4) and a legacy-service on Spring Boot 3.2 with older pinned libraries.
 */
@SpringBootTest(properties = "spring.datasource.url=jdbc:h2:mem:real;IGNORECASE=TRUE")
@Transactional
class RealSbomTest {

    @Autowired
    private SbomService sboms;

    @BeforeEach
    void setUp() {
        sboms.ingest(Path.of("samples/sbom-cli.cdx.json"));
        sboms.ingest(Path.of("samples/legacy-service.cdx.json"));
    }

    @Test
    void ingestsAllComponents() {
        var docs = sboms.listDocuments();
        assertEquals(List.of("legacy-service", "sbom-cli"), docs.stream().map(d -> d.name()).toList());
        assertEquals(73, docs.get(0).componentCount());
        assertEquals(58, docs.get(1).componentCount());
        assertEquals("build", docs.get(0).lifecycle()); // CycloneDX metadata.lifecycles[].phase
    }

    @Test
    void sameComponentAtDifferentVersions() {
        List<QueryResult> all = sboms.findByComponent("hibernate-core", null);
        assertEquals(List.of("6.3.1.Final", "7.4.5.Final"), all.stream().map(QueryResult::version).toList());

        List<QueryResult> old = sboms.findByComponent("hibernate-core", "6.3.1.Final");
        assertEquals(1, old.size());
        assertEquals("legacy-service", old.get(0).documentName());
    }

    @Test
    void findsVulnerableLog4jOnlyInLegacyService() {
        List<QueryResult> results = sboms.findByComponent("log4j-core", "2.14.1");
        assertEquals(1, results.size());
        assertEquals("legacy-service", results.get(0).documentName());
    }

    @Test
    void licenseSharedByManyComponentsAcrossDocuments() {
        List<QueryResult> epl = sboms.findByLicense("EPL-2.0");
        assertTrue(epl.size() > 5);
        assertEquals(2, epl.stream().map(QueryResult::documentName).distinct().count());
    }

    @Test
    void variedLicensesAreAllQueryable() {
        for (String license : List.of("Apache-2.0", "MIT", "BSD-3-Clause", "EPL-2.0", "LGPL-2.1-only",
                "MPL-2.0", "GPL-2.0-with-classpath-exception", "BSD-4-Clause")) {
            assertTrue(!sboms.findByLicense(license).isEmpty(), "no components for " + license);
        }
    }
}
